/* Generated by tools/gen_h264_tables.py - do not edit by hand.
 *
 * Copyright (c) 2026 BC-250 Project
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * The constant tables of Rec. ITU-T H.264. Extracted mechanically from
 * FFmpeg n8.1.2 (LGPL-2.1-or-later, used here under GPL-3.0-only as permitted
 * by LGPL-2.1 clause 3) so that every value is provably the standard's own.
 * Re-run the generator to reproduce this file byte for byte.
 */

#ifndef BC250_H264_DEC_TABLES_H
#define BC250_H264_DEC_TABLES_H

#include <stdint.h>

extern const int8_t h264d_cabac_init_I[1024][2];
extern const int8_t h264d_cabac_init_PB[3][1024][2];
extern const uint16_t h264d_sig_coeff_offset[2][14];
extern const uint16_t h264d_last_coeff_offset[2][14];
extern const uint16_t h264d_abs_level_offset[14];
extern const uint8_t h264d_sig_coeff_offset_8x8[2][63];
extern const uint8_t h264d_sig_coeff_offset_dc[7];
extern const uint8_t h264d_last_coeff_offset_8x8[63];
extern const uint8_t h264d_dequant4_init[6][3];
extern const uint8_t h264d_dequant8_init[6][6];
extern const uint8_t h264d_dequant8_init_scan[16];
extern const uint8_t h264d_chroma_qp[52];
extern const uint8_t h264d_golomb_to_intra4x4_cbp[48];
extern const uint8_t h264d_golomb_to_inter_cbp[48];
extern const uint8_t h264d_chroma_dc_scan[4];
extern const uint8_t h264d_zigzag4[16];
extern const uint8_t h264d_zigzag8[64];
extern const uint8_t h264d_coeff_token_len[4][68];
extern const uint8_t h264d_coeff_token_bits[4][68];
extern const uint8_t h264d_chroma_dc_coeff_token_len[20];
extern const uint8_t h264d_chroma_dc_coeff_token_bits[20];
extern const uint8_t h264d_total_zeros_len[16][16];
extern const uint8_t h264d_total_zeros_bits[16][16];
extern const uint8_t h264d_chroma_dc_total_zeros_len[3][4];
extern const uint8_t h264d_chroma_dc_total_zeros_bits[3][4];
extern const uint8_t h264d_run_len[7][16];
extern const uint8_t h264d_run_bits[7][16];

#endif /* BC250_H264_DEC_TABLES_H */
