/*
 * Copyright (c) 2026 BC-250 Project
 * SPDX-License-Identifier: GPL-3.0-only
 *
 * hevc_dec_tables.h - generated by tools/gen_hevc_tables.py; do not edit.
 *
 * The normative constant tables of Rec. ITU-T H.265, extracted from FFmpeg
 * n8.1.2 (LGPL-2.1-or-later, used here under GPL-3.0-only as clause 3 of the
 * LGPL permits). Re-run the generator to check any of them.
 */

#ifndef BC250_HEVC_DEC_TABLES_H
#define BC250_HEVC_DEC_TABLES_H

#include <stdint.h>

#define HEVCD_CTX 179

/* Where each syntax element's contexts start, clause 9.3.4.2. */
enum {
    HEVCD_CTX_SAO_MERGE_FLAG = 0,
    HEVCD_CTX_SAO_TYPE_IDX = 1,
    HEVCD_CTX_SAO_EO_CLASS = 2,
    HEVCD_CTX_SAO_BAND_POSITION = 2,
    HEVCD_CTX_SAO_OFFSET_ABS = 2,
    HEVCD_CTX_SAO_OFFSET_SIGN = 2,
    HEVCD_CTX_END_OF_SLICE_FLAG = 2,
    HEVCD_CTX_SPLIT_CODING_UNIT_FLAG = 2,
    HEVCD_CTX_CU_TRANSQUANT_BYPASS_FLAG = 5,
    HEVCD_CTX_SKIP_FLAG = 6,
    HEVCD_CTX_CU_QP_DELTA = 9,
    HEVCD_CTX_PRED_MODE_FLAG = 12,
    HEVCD_CTX_PART_MODE = 13,
    HEVCD_CTX_PCM_FLAG = 17,
    HEVCD_CTX_PREV_INTRA_LUMA_PRED_FLAG = 17,
    HEVCD_CTX_MPM_IDX = 18,
    HEVCD_CTX_REM_INTRA_LUMA_PRED_MODE = 18,
    HEVCD_CTX_INTRA_CHROMA_PRED_MODE = 18,
    HEVCD_CTX_MERGE_FLAG = 20,
    HEVCD_CTX_MERGE_IDX = 21,
    HEVCD_CTX_INTER_PRED_IDC = 22,
    HEVCD_CTX_REF_IDX_L0 = 27,
    HEVCD_CTX_REF_IDX_L1 = 29,
    HEVCD_CTX_ABS_MVD_GREATER0_FLAG = 31,
    HEVCD_CTX_ABS_MVD_GREATER1_FLAG = 33,
    HEVCD_CTX_ABS_MVD_MINUS2 = 35,
    HEVCD_CTX_MVD_SIGN_FLAG = 35,
    HEVCD_CTX_MVP_LX_FLAG = 35,
    HEVCD_CTX_NO_RESIDUAL_DATA_FLAG = 36,
    HEVCD_CTX_SPLIT_TRANSFORM_FLAG = 37,
    HEVCD_CTX_CBF_LUMA = 40,
    HEVCD_CTX_CBF_CB_CR = 42,
    HEVCD_CTX_TRANSFORM_SKIP_FLAG = 47,
    HEVCD_CTX_EXPLICIT_RDPCM_FLAG = 49,
    HEVCD_CTX_EXPLICIT_RDPCM_DIR_FLAG = 51,
    HEVCD_CTX_LAST_SIGNIFICANT_COEFF_X_PREFIX = 53,
    HEVCD_CTX_LAST_SIGNIFICANT_COEFF_Y_PREFIX = 71,
    HEVCD_CTX_LAST_SIGNIFICANT_COEFF_X_SUFFIX = 89,
    HEVCD_CTX_LAST_SIGNIFICANT_COEFF_Y_SUFFIX = 89,
    HEVCD_CTX_SIGNIFICANT_COEFF_GROUP_FLAG = 89,
    HEVCD_CTX_SIGNIFICANT_COEFF_FLAG = 93,
    HEVCD_CTX_COEFF_ABS_LEVEL_GREATER1_FLAG = 137,
    HEVCD_CTX_COEFF_ABS_LEVEL_GREATER2_FLAG = 161,
    HEVCD_CTX_COEFF_ABS_LEVEL_REMAINING = 167,
    HEVCD_CTX_COEFF_SIGN_FLAG = 167,
    HEVCD_CTX_LOG2_RES_SCALE_ABS = 167,
    HEVCD_CTX_RES_SCALE_SIGN_FLAG = 175,
    HEVCD_CTX_CU_CHROMA_QP_OFFSET_FLAG = 177,
    HEVCD_CTX_CU_CHROMA_QP_OFFSET_IDX = 178,
};

/* Every context's initial state, by [initType * 52 + SliceQpY].
 * Packed as the engine reads it: (pStateIdx << 1) | valMPS with
 * pStateIdx counted from the other end, the same convention the
 * H.264 engine uses. */
extern const uint8_t hevcd_ctx_init[3 * 52][HEVCD_CTX];

extern const uint8_t hevcd_diag4_x[16];
extern const uint8_t hevcd_diag4_y[16];
extern const uint8_t hevcd_diag8_x[64];
extern const uint8_t hevcd_diag8_y[64];
extern const uint8_t hevcd_diag2_x[4];
extern const uint8_t hevcd_diag2_y[4];
extern const uint8_t hevcd_horiz2_x[4];
extern const uint8_t hevcd_horiz2_y[4];
extern const uint8_t hevcd_horiz4_x[16];
extern const uint8_t hevcd_horiz4_y[16];
extern const uint8_t hevcd_level_scale[6];
extern const uint8_t hevcd_ctx_idx_map[80];
extern const uint8_t hevcd_tc[54];
extern const uint8_t hevcd_beta[52];
extern const uint8_t hevcd_sao_tab[8];
extern const uint8_t hevcd_qp_c[14];
extern const uint8_t hevcd_diag2_inv[2][2];
extern const uint8_t hevcd_diag4_inv[4][4];
extern const uint8_t hevcd_diag8_inv[8][8];
extern const uint8_t hevcd_horiz8_inv[8][8];
extern const int8_t hevcd_epel[8][4];
extern const int8_t hevcd_qpel[4][8];
extern const int16_t hevcd_intra_angle[33];
extern const int16_t hevcd_inv_angle[15];

#endif /* BC250_HEVC_DEC_TABLES_H */
